name: deploy-container

# ? First specify the event condition to watch
on:
  # Every time a push event occured on branch master where there is changes in container folder
  push:
    branches:
      - master
    paths:
      - 'packages/container/**'

# ? Setup/initialize
defaults:
  run:
    # Set the execution command in this folder 
    working-directory: packages/container

# ? The actual job for github action to do
jobs:
  build:
    runs-on: ubuntu-latest # will run this on linux-based github-hosted VMs
    environment: production

    steps:
      - uses: actions/checkout@v2 # this is reusable action provided by github action communities
      - run: npm install
      - run: npm run build

      # Programatic access to AWS S3, since we want to upload the dist folder to AWS S3
      - uses: shinyinc/action-aws-cli@v1.2
      - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest # point is we specify the AWS S3 bucket to host our bundled production file, which is located in /container/latest AWS S3 bucket path
        env: # get secrets from github repo .env,
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

        # Basically tell aws cloudfront (via CLI) to invalidate the index.html cache.
      - run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/container/latest/index.html"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}